name: 'GitHub Actions bitcoin-bubble-index Bot'
 
on:
  push:
  schedule:
    - cron: '0 21 * * *'


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      working-directory: ./original_data
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: getdata and process data
      working-directory: ./original_data
      run: |
        python getdata.py
        python process_data.py
    
    - uses: ad-m/github-push-action@v0.5.0
    - name: Commit files
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git commit -m "Add changes" -a
      with:
        github_token: ${{ secrets.GITHUB_TOKEN_1 }}
        force: true
